-- 1
CREATE TABLE MEDEWERKERS2 AS SELECT * FROM MEDEWERKERS;

-- 1.2
ALTER TABLE MEDEWERKERS2
ADD GESLACHT VARCHAR(16);

--1.3
ALTER TABLE MEDEWERKERS2
ADD CONSTRAINT GESLACHT_CHECK CHECK(GESLACHT = 'M' OR GESLACHT = 'V');

--1.4
INSERT INTO MEDEWERKERS2 (MNR, NAAM, VOORL, FUNCTIE, CHEF, GBDATUM, MAANDSAL, COMM, AFD, GESLACHT)
VALUES (NULL, 'Jos', 'J', NULL, NULL, '2008-11-11', 0, NULL, NULL, 'MA');

--2.1
DROP SEQUENCE AFDELING_NR_SEQ;

CREATE SEQUENCE AFDELING_NR_SEQ
    START WITH 50
    INCREMENT BY 10;

--2.2
INSERT INTO AFDELINGEN VALUES (AFDELING_NR_SEQ.NEXTVAL,'PAND', 'GRONINGEN', NULL);
INSERT INTO AFDELINGEN VALUES (AFDELING_NR_SEQ.NEXTVAL,'VUILNISBELT', 'ZAANDAM', NULL);

SELECT * FROM AFDELINGEN;

--2.3
ALTER TABLE AFDELINGEN 
    MODIFY ANR NUMBER(3);
    
--3
DROP TABLE ADRESSEN;

CREATE TABLE ADRESSEN 
( 
    POSTCODE      CHAR(6),
    HUISNUMMER    NUMBER(6),
    INGANGSDATUM  DATE NOT NULL,
    EINDDATUM     DATE,
    TELEFOON      NUMBER(10) UNIQUE,
    MED_MNR       NUMBER(4),
    CONSTRAINT    ADR_PK PRIMARY KEY (POSTCODE, HUISNUMMER, INGANGSDATUM),
    CONSTRAINT    ADR_FK FOREIGN KEY (MED_MNR) REFERENCES MEDEWERKERS(MNR)
);

ALTER TABLE ADRESSEN ADD CONSTRAINT ADR_CHK CHECK (INGANGSDATUM < EINDDATUM);
